version: '3.7'
services:
  postgresql_db:
    image: postgres:14
    restart: always
    volumes:
      - ./api/data/db:/var/lib/postgresql/data
      - ./api/sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./api/sql/fill_table.sql:/docker-entrypoint-initdb.d/fill_table.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dependix
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    container_name: api
    build: ./api
    ports:
      - "4545:4545"
    restart: on-failure
    depends_on:
      - postgresql_db
    links:
      - postgresql_db
  react:
    build: ./react
    container_name: REACT
    ports: 
      - "3000:3000"
    stdin_open: true
    tty: true
